import Head from "next/head";
import Link from "next/link";

import { CirclePlus } from "lucide-react";

import { api } from "~/utils/api";
import { db } from "~/server/db";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-start justify-start bg-black p-6 text-white">
        <header className="my-8">
          <h1 className="text-5xl font-bold tracking-tight text-white sm:text-[5rem]">
            Prise de vue
          </h1>
          <p className="mt-2 text-gray-400">
            Enregistrez vos prises de vue et vos émotions
          </p>
        </header>
        <h2 className="text-3xl font-semibold tracking-tight text-white sm:text-[5rem]">
          Votre historique
        </h2>
        <div className="h-full overflow-y-auto"></div>

        <button className="flex w-full items-center justify-center gap-2 rounded-md bg-white py-3 font-bold text-black">
          <CirclePlus />
          Ajouter
        </button>
      </main>
    </>
  );
}
